name: suan_market_app
description: Suan Mouakhom Market - Buyer, Seller, and Admin app (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  image_picker: ^1.2.2
  crop_your_image: ^2.0.0
  image: ^4.2.0
  qr_flutter: ^4.1.0
  geolocator: ^14.0.2
  geocoding: ^5.0.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  google_mlkit_text_recognition: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  
  # Add these lines to fix the sizing inside the Android container:
  adaptive_icon_background: "assets/icon/app_icon.png" 
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_foreground_inset: 16  # Reduces the safe-zone padding to 0 so the icon fills the entire space

flutter:
  uses-material-design: true